services:
  - type: web
    name: scanora-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: ELASTIC_NODE
        sync: false
      - key: ELASTIC_API_KEY
        sync: false
